
services:

    software-shinobi-linux:
        
        container_name: software-shinobi-linux

        build: 

            context: .

            dockerfile: Dockerfile

        image: softwareshinobi/embanet-ubuntu-linux:sian

        hostname: sian

        domainname: sian.embanet.online

        ports:

            - "2222:22"
